name: BUILD ENV (RUBY) IMAGE

on:
  push:
    branches:
      - main
    paths:
      - 'server/containers/ruby/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/containers/ruby/Dockerfile
          platforms: linux/amd64
          push: true
          tags: baealex/mymydev-env-ruby:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
